services:
  backend:
    build: "./backend"
    ports:
      - "8080:8080"
    env_file:
      - "./backend/.env"
    depends_on:
      - fullmetal-alchemist-db

  fullmetal-alchemist-db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fullmetal_alchemist
      MYSQL_USER: alchemist
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - fullmetal-alchemist-mysql-data:/var/lib/mysql

volumes:
  fullmetal-alchemist-mysql-data:
